# Dockerfile.dev

# Use the official Go image as the base image
FROM golang:1.23.1

# Install Vim and Go development tools
# Install Vim and other tools
RUN apt-get update && \
    apt-get install -y vim curl && \
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
    go install golang.org/x/tools/gopls@latest && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on
EXPOSE 8080

# Default command to run a bash shell
CMD ["bash"]

